import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'; // 1. 导入 Script 组件

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {children}
        
        {/* 2. 使用 Next.js 的 Script 组件来加载 Google Analytics */}
        {/*    这才是正确且安全的方式 */}
        <Script 
          src="https://www.googletagmanager.com/gtag/js?id=G-LKWQLR5STV" 
          strategy="afterInteractive" 
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-LKWQLR5STV');
          `}
        </Script>

      </body>
    </html>
  );
}